id: P004244
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5328
  title: ཐུབ་བསྟན་རིས་སུ་མ་ཆད་པའི་བླ་མ་མཆོད་པ་དང་ལྷན་ཐབས་བཅས་
  author: ''
  volumes:
    559b40c71e374b44a2d9d13d9d5271b2:
      image_group_id: I1KG5332
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
