id: I27245EA2
legacy_id: P004244
ocr_import_info:
  bdrc_scan_id: W1KG5328
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T18:56:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:15:10.075405+00:00'
last_modified: 2022-09-01 01:15:18.905862
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5328
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5328
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུབ་བསྟན་རིས་སུ་མ་ཆད་པའི་བླ་མ་མཆོད་པ་དང་ལྷན་ཐབས་བཅས།
statistics:
  ocr_word_mean_confidence_index: 0.753024772795951
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG5332:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5332
      total_pages: 234
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5332.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.753024772795951
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
